// Расширение базы: +200 правил и +150 ГОСТ
// Цель: довести общее количество правил до ~300+, ГОСТ до ~570+
import { db } from '../src/lib/db'

// ============ ДОПОЛНИТЕЛЬНЫЕ ГОСТ (категории: крепеж, трубопроводы, окраска, изоляция, электротехника, безопасность) ============
const MORE_STANDARDS = [
  // Крепёж (болты/гайки/шайбы/шпильки)
  { code: 'ГОСТ 7795-70', name: 'Болты с шестигранной уменьшенной головкой класса точности В', type: 'GOST', scope: 'Болты', category: 'materials', publishedAt: '1970' },
  { code: 'ГОСТ 7808-70', name: 'Болты с шестигранной головкой уменьшенного размера класса точности А', type: 'GOST', scope: 'Болты (А, малые)', category: 'materials', publishedAt: '1970' },
  { code: 'ГОСТ 15589-70', name: 'Болты с шестигранной головкой класса точности С', type: 'GOST', scope: 'Болты (С)', category: 'materials', publishedAt: '1970' },
  { code: 'ГОСТ 15590-70', name: 'Болты с шестигранной уменьшенной головкой класса точности С', type: 'GOST', scope: 'Болты (С, малые)', category: 'materials', publishedAt: '1970' },
  { code: 'ГОСТ 15591-70', name: 'Болты с полукруглой головкой класса точности С', type: 'GOST', scope: 'Болты полукруглые', category: 'materials', publishedAt: '1970' },
  { code: 'ГОСТ 7783-81', name: 'Болты с полукруглой головкой и усом. Конструкция и размеры', type: 'GOST', scope: 'Болты с усом', category: 'materials', publishedAt: '1981' },
  { code: 'ГОСТ 7785-81', name: 'Болты откидные. Конструкция и размеры', type: 'GOST', scope: 'Болты откидные', category: 'materials', publishedAt: '1981' },
  { code: 'ГОСТ 3033-79', name: 'Болты костыльковые. Конструкция и размеры', type: 'GOST', scope: 'Болты костыльковые', category: 'materials', publishedAt: '1979' },
  { code: 'ГОСТ 9065-75', name: 'Болты судовые. Конструкция и размеры', type: 'GOST', scope: 'Судовые болты', category: 'shipbuilding', publishedAt: '1975' },
  { code: 'ГОСТ 5916-70', name: 'Гайки шестигранные низкие класса точности В', type: 'GOST', scope: 'Гайки низкие', category: 'materials', publishedAt: '1970' },
  { code: 'ГОСТ 5918-73', name: 'Гайки шестигранные прорезные. Конструкция и размеры', type: 'GOST', scope: 'Гайки прорезные', category: 'materials', publishedAt: '1973' },
  { code: 'ГОСТ 5919-73', name: 'Гайки шестигранные корончатые. Конструкция и размеры', type: 'GOST', scope: 'Гайки корончатые', category: 'materials', publishedAt: '1973' },
  { code: 'ГОСТ 5929-70', name: 'Гайки шестигранные низкие класса точности А', type: 'GOST', scope: 'Гайки низкие (А)', category: 'materials', publishedAt: '1970' },
  { code: 'ГОСТ 5931-70', name: 'Гайки шестигранные высокие класса точности А', type: 'GOST', scope: 'Гайки высокие (А)', category: 'materials', publishedAt: '1970' },
  { code: 'ГОСТ 10605-94', name: 'Гайки шестигранные с размером под ключ свыше 48 мм. Технические условия', type: 'GOST', scope: 'Гайки крупные', category: 'materials', publishedAt: '1994' },
  { code: 'ГОСТ 10606-72', name: 'Гайки шестигранные特别 высокие. Конструкция и размеры', type: 'GOST', scope: 'Гайки особовысокие', category: 'materials', publishedAt: '1972' },
  { code: 'ГОСТ 11371-78', name: 'Шайбы. Технические условия', type: 'GOST', scope: 'Шайбы ТУ', category: 'materials', publishedAt: '1978' },
  { code: 'ГОСТ 6402-70', name: 'Шайбы пружинные. Технические условия', type: 'GOST', scope: 'Шайбы пружинные (гровер)', category: 'materials', publishedAt: '1970' },
  { code: 'ГОСТ 13463-77', name: 'Шайбы стопорные многолапчатые', type: 'GOST', scope: 'Шайбы стопорные', category: 'materials', publishedAt: '1977' },
  { code: 'ГОСТ 13465-77', name: 'Шайбы стопорные с носком. Конструкция и размеры', type: 'GOST', scope: 'Шайбы с носком', category: 'materials', publishedAt: '1977' },
  { code: 'ГОСТ 10462-81', name: 'Шайбы быстросъёмные. Конструкция и размеры', type: 'GOST', scope: 'Шайбы быстросъёмные', category: 'materials', publishedAt: '1981' },
  { code: 'ГОСТ 9066-75', name: 'Шайбы судовые. Конструкция и размеры', type: 'GOST', scope: 'Судовые шайбы', category: 'shipbuilding', publishedAt: '1975' },
  { code: 'ГОСТ 9064-75', name: 'Гайки судовые. Конструкция и размеры', type: 'GOST', scope: 'Судовые гайки', category: 'shipbuilding', publishedAt: '1975' },
  { code: 'ГОСТ 9067-75', name: 'Шпильки судовые. Конструкция и размеры', type: 'GOST', scope: 'Судовые шпильки', category: 'shipbuilding', publishedAt: '1975' },
  { code: 'ГОСТ 22042-76', name: 'Шпильки с ввинчиваемым концом длиной 1,25d. Класс точности В', type: 'GOST', scope: 'Шпильки 1.25d', category: 'materials', publishedAt: '1976' },
  { code: 'ГОСТ 22043-76', name: 'Шпильки с ввинчиваемым концом длиной 1,6d. Класс точности В', type: 'GOST', scope: 'Шпильки 1.6d', category: 'materials', publishedAt: '1976' },
  { code: 'ГОСТ 11765-71', name: 'Шпильки с ввинчиваемым концом класса точности А', type: 'GOST', scope: 'Шпильки (А)', category: 'materials', publishedAt: '1971' },
  { code: 'ГОСТ 24679-81', name: 'Болты с фланцем шестигранные. Конструкция и размеры', type: 'GOST', scope: 'Болты с фланцем', category: 'materials', publishedAt: '1981' },
  { code: 'ГОСТ 28423-97', name: 'Болты самонарезающие с потайной головкой. Технические условия', type: 'GOST', scope: 'Саморезы потайные', category: 'materials', publishedAt: '1997' },
  { code: 'ГОСТ 11652-80', name: 'Винты самонарезающие с полукруглой головкой. Конструкция и размеры', type: 'GOST', scope: 'Саморезы полукруглые', category: 'materials', publishedAt: '1980' },
  // Трубопроводы
  { code: 'ГОСТ 3262-75', name: 'Трубы стальные водогазопроводные. Технические условия', type: 'GOST', scope: 'ВГП трубы', category: 'shipbuilding', publishedAt: '1975' },
  { code: 'ГОСТ 8731-87', name: 'Трубы стальные бесшовные горячедеформированные. Технические условия', type: 'GOST', scope: 'Бесшовные трубы', category: 'shipbuilding', publishedAt: '1987' },
  { code: 'ГОСТ 8732-78', name: 'Трубы стальные бесшовные горячедеформированные. Сортамент', type: 'GOST', scope: 'Сортамент бесшовных', category: 'shipbuilding', publishedAt: '1978' },
  { code: 'ГОСТ 8733-74', name: 'Трубы стальные бесшовные холоднодеформированные. Технические условия', type: 'GOST', scope: 'Холоднодеформ. трубы', category: 'shipbuilding', publishedAt: '1974' },
  { code: 'ГОСТ 8734-75', name: 'Трубы стальные бесшовные холоднодеформированные. Сортамент', type: 'GOST', scope: 'Сортамент холоднодеформ.', category: 'shipbuilding', publishedAt: '1975' },
  { code: 'ГОСТ 9940-81', name: 'Трубы бесшовные горячедеформированные из коррозионно-стойкой стали', type: 'GOST', scope: 'Нержавеющие трубы', category: 'shipbuilding', publishedAt: '1981' },
  { code: 'ГОСТ 9941-81', name: 'Трубы бесшовные холодно- и теплодеформированные из коррозионно-стойкой стали', type: 'GOST', scope: 'Нержавеющие холоднодеформ.', category: 'shipbuilding', publishedAt: '1981' },
  { code: 'ГОСТ 10704-91', name: 'Трубы стальные электросварные прямошовные. Сортамент', type: 'GOST', scope: 'Электросварные трубы', category: 'shipbuilding', publishedAt: '1991' },
  { code: 'ГОСТ 10705-80', name: 'Трубы стальные электросварные прямошовные. Технические условия', type: 'GOST', scope: 'Электросварные ТУ', category: 'shipbuilding', publishedAt: '1980' },
  { code: 'ГОСТ 20295-85', name: 'Трубы стальные сварные для магистральных газонефтепроводов', type: 'GOST', scope: 'Магистральные трубы', category: 'shipbuilding', publishedAt: '1985' },
  { code: 'ГОСТ 617-2006', name: 'Трубы медные. Технические условия', type: 'GOST', scope: 'Медные трубы', category: 'shipbuilding', publishedAt: '2006' },
  { code: 'ГОСТ 21646-2003', name: 'Трубы медные для теплообменников. Технические условия', type: 'GOST', scope: 'Трубы для теплообменников', category: 'shipbuilding', publishedAt: '2003' },
  { code: 'ГОСТ 18475-82', name: 'Трубы латунные. Технические условия', type: 'GOST', scope: 'Латунные трубы', category: 'shipbuilding', publishedAt: '1982' },
  { code: 'ГОСТ 23697-79', name: 'Трубы алюминиевые. Технические условия', type: 'GOST', scope: 'Алюминиевые трубы', category: 'shipbuilding', publishedAt: '1979' },
  { code: 'ГОСТ 18599-2001', name: 'Трубы напорные из полиэтилена. Технические условия', type: 'GOST', scope: 'ПЭ трубы', category: 'shipbuilding', publishedAt: '2001' },
  { code: 'ГОСТ 53959-2010', name: 'Трубы напорные многослойные для систем водоснабжения', type: 'GOST', scope: 'Многослойные трубы', category: 'shipbuilding', publishedAt: '2010' },
  { code: 'ГОСТ 3326-86', name: 'Трубы и муфты чугунные напорные. Технические условия', type: 'GOST', scope: 'Чугунные трубы', category: 'shipbuilding', publishedAt: '1986' },
  // Фитинги трубопроводов
  { code: 'ГОСТ 17375-2001', name: 'Детали трубопроводов бесшовные приварные из углеродистой и низколегированной стали. Отводы', type: 'GOST', scope: 'Отводы приварные', category: 'shipbuilding', publishedAt: '2001' },
  { code: 'ГОСТ 17376-2001', name: 'Детали трубопроводов. Тройники', type: 'GOST', scope: 'Тройники', category: 'shipbuilding', publishedAt: '2001' },
  { code: 'ГОСТ 17378-2001', name: 'Детали трубопроводов. Переходы', type: 'GOST', scope: 'Переходы', category: 'shipbuilding', publishedAt: '2001' },
  { code: 'ГОСТ 17379-2001', name: 'Детали трубопроводов. Заглушки', type: 'GOST', scope: 'Заглушки', category: 'shipbuilding', publishedAt: '2001' },
  { code: 'ГОСТ 17380-2001', name: 'Детали трубопроводов бесшовные приварные из углеродистой и низколегированной стали. Общие ТУ', type: 'GOST', scope: 'Детали трубопроводов ТУ', category: 'shipbuilding', publishedAt: '2001' },
  // Фланцы
  { code: 'ГОСТ 3326-86', name: 'Фланцы арматуры, соединительных частей и трубопроводов. Параметры', type: 'GOST', scope: 'Фланцы параметры', category: 'shipbuilding', publishedAt: '1986' },
  { code: 'ГОСТ 12815-80', name: 'Фланцы арматуры, соединительных частей и трубопроводов. Типы и параметры', type: 'GOST', scope: 'Фланцы типы', category: 'shipbuilding', publishedAt: '1980' },
  { code: 'ГОСТ 12816-80', name: 'Фланцы арматуры. Общие ТУ', type: 'GOST', scope: 'Фланцы ТУ', category: 'shipbuilding', publishedAt: '1980' },
  { code: 'ГОСТ 12817-80', name: 'Фланцы литые из серого чугуна. Конструкция и размеры', type: 'GOST', scope: 'Фланцы чугунные литые', category: 'shipbuilding', publishedAt: '1980' },
  { code: 'ГОСТ 12818-80', name: 'Фланцы литые из ковкого чугуна. Конструкция и размеры', type: 'GOST', scope: 'Фланцы ковкий чугун', category: 'shipbuilding', publishedAt: '1980' },
  { code: 'ГОСТ 12819-80', name: 'Фланцы литые стальные. Конструкция и размеры', type: 'GOST', scope: 'Фланцы стальные литые', category: 'shipbuilding', publishedAt: '1980' },
  { code: 'ГОСТ 12820-80', name: 'Фланцы стальные плоские приварные. Конструкция и размеры', type: 'GOST', scope: 'Фланцы плоские приварные', category: 'shipbuilding', publishedAt: '1980' },
  { code: 'ГОСТ 12821-80', name: 'Фланцы стальные приварные встык. Конструкция и размеры', type: 'GOST', scope: 'Фланцы приварные встык', category: 'shipbuilding', publishedAt: '1980' },
  { code: 'ГОСТ 12822-80', name: 'Фланцы стальные свободные на приварном кольце. Конструкция и размеры', type: 'GOST', scope: 'Фланцы свободные', category: 'shipbuilding', publishedAt: '1980' },
  // Окраска и покрытия
  { code: 'ГОСТ 9.032-74', name: 'ЕСЗКС. Покрытия лакокрасочные. Группы, технические требования и обозначения', type: 'GOST', scope: 'Лакокрасочные покрытия', category: 'shipbuilding', publishedAt: '1974' },
  { code: 'ГОСТ 9.401-91', name: 'ЕСЗКС. Покрытия лакокрасочные. Общие требования и методы ускоренных испытаний', type: 'GOST', scope: 'Испытания покрытий', category: 'shipbuilding', publishedAt: '1991' },
  { code: 'ГОСТ 9.407-2015', name: 'ЕСЗКС. Покрытия лакокрасочные. Метод оценки внешнего вида', type: 'GOST', scope: 'Внешний вид покрытий', category: 'shipbuilding', publishedAt: '2015' },
  { code: 'ГОСТ 9.410-88', name: 'ЕСЗКС. Покрытия порошковые полимерные. Типы и технические требования', type: 'GOST', scope: 'Порошковые покрытия', category: 'shipbuilding', publishedAt: '1988' },
  { code: 'ГОСТ 9.411-87', name: 'ЕСЗКС. Покрытия порошковые. Метод определения толщины', type: 'GOST', scope: 'Толщина покрытий', category: 'shipbuilding', publishedAt: '1987' },
  { code: 'ГОСТ 9.414-86', name: 'ЕСЗКС. Покрытия порошковые. Метод определения адгезии', type: 'GOST', scope: 'Адгезия покрытий', category: 'shipbuilding', publishedAt: '1986' },
  { code: 'ГОСТ 5631-79', name: 'Лак БТ-577 и грунтовка ГФ-017. ТУ', type: 'GOST', scope: 'Грунтовка ГФ-017', category: 'shipbuilding', publishedAt: '1979' },
  { code: 'ГОСТ 12707-77', name: 'Грунтовки марок ГФ-021 и ГФ-0163', type: 'GOST', scope: 'Грунтовки ГФ', category: 'shipbuilding', publishedAt: '1977' },
  { code: 'ГОСТ 25129-82', name: 'Грунтовка ГФ-0119. Технические условия', type: 'GOST', scope: 'Грунтовка ГФ-0119', category: 'shipbuilding', publishedAt: '1982' },
  { code: 'ГОСТ 7313-75', name: 'Эмали ХС-413. Технические условия', type: 'GOST', scope: 'Эмаль ХС-413', category: 'shipbuilding', publishedAt: '1975' },
  { code: 'ГОСТ 21824-76', name: 'Эмали ХС-717, ХС-717А. Технические условия', type: 'GOST', scope: 'Эмаль ХС-717', category: 'shipbuilding', publishedAt: '1976' },
  { code: 'ГОСТ 23494-78', name: 'Грунтовка ХС-010. Технические условия', type: 'GOST', scope: 'Грунтовка ХС-010', category: 'shipbuilding', publishedAt: '1978' },
  { code: 'ГОСТ 926-82', name: 'Эмали и грунтовки пентафталевые. ТУ', type: 'GOST', scope: 'Пентафталевые эмали', category: 'shipbuilding', publishedAt: '1982' },
  { code: 'ГОСТ 6465-76', name: 'Эмали нитроцеллюлозные. ТУ', type: 'GOST', scope: 'Нитроэмали', category: 'shipbuilding', publishedAt: '1976' },
  { code: 'ГОСТ 10503-71', name: 'Краски масляные. ТУ', type: 'GOST', scope: 'Масляные краски', category: 'shipbuilding', publishedAt: '1971' },
  { code: 'ГОСТ 20833-75', name: 'Шпатлёвки. Общие ТУ', type: 'GOST', scope: 'Шпатлёвки', category: 'shipbuilding', publishedAt: '1975' },
  // Изоляция и теплоизоляция
  { code: 'ГОСТ 10499-95', name: 'Изделия теплоизоляционные из стеклянного штапельного волокна. ТУ', type: 'GOST', scope: 'Стекловолокно', category: 'shipbuilding', publishedAt: '1995' },
  { code: 'ГОСТ 21880-2011', name: 'Маты из минеральной ваты. ТУ', type: 'GOST', scope: 'Маты минватные', category: 'shipbuilding', publishedAt: '2011' },
  { code: 'ГОСТ 9573-96', name: 'Плиты из минеральной ваты на синтетическом связующем. ТУ', type: 'GOST', scope: 'Плиты минватные', category: 'shipbuilding', publishedAt: '1996' },
  { code: 'ГОСТ 22950-78', name: 'Плиты из минеральной ваты повышенной жёсткости. ТУ', type: 'GOST', scope: 'Плиты повышенной жёсткости', category: 'shipbuilding', publishedAt: '1978' },
  { code: 'ГОСТ 16381-77', name: 'Материалы и изделия теплоизоляционные. Классификация', type: 'GOST', scope: 'Классификация изоляции', category: 'shipbuilding', publishedAt: '1977' },
  { code: 'ГОСТ 4640-2011', name: 'Вата минеральная. ТУ', type: 'GOST', scope: 'Минвата', category: 'shipbuilding', publishedAt: '2011' },
  { code: 'ГОСТ 15588-2014', name: 'Плиты пенополистирольные. ТУ', type: 'GOST', scope: 'Пенополистирол', category: 'shipbuilding', publishedAt: '2014' },
  { code: 'ГОСТ 20916-87', name: 'Плиты теплоизоляционные из пенопласта. ТУ', type: 'GOST', scope: 'Пенопласт', category: 'shipbuilding', publishedAt: '1987' },
  { code: 'ГОСТ 17177-94', name: 'Материалы и изделия строительные теплоизоляционные. Методы испытаний', type: 'GOST', scope: 'Испытания изоляции', category: 'shipbuilding', publishedAt: '1994' },
  // Электротехника
  { code: 'ГОСТ 12.1.009-76', name: 'ССБТ. Электробезопасность. Термины и определения', type: 'GOST', scope: 'Электробезопасность', category: 'shipbuilding', publishedAt: '1976' },
  { code: 'ГОСТ 12.1.019-79', name: 'ССБТ. Электробезопасность. Общие требования', type: 'GOST', scope: 'Электробезопасность общие', category: 'shipbuilding', publishedAt: '1979' },
  { code: 'ГОСТ 12.1.030-81', name: 'ССБТ. Электробезопасность. Защитное заземление, зануление', type: 'GOST', scope: 'Заземление', category: 'shipbuilding', publishedAt: '1981' },
  { code: 'ГОСТ 12.1.038-82', name: 'ССБТ. Электробезопасность. Предельно допустимые значения напряжений', type: 'GOST', scope: 'ПД напряжений', category: 'shipbuilding', publishedAt: '1982' },
  { code: 'ГОСТ 30331.1-2013', name: 'Электроустановки низковольтные. Часть 1. Основные положения', type: 'GOST', scope: 'Электроустановки', category: 'shipbuilding', publishedAt: '2013' },
  { code: 'ГОСТ 50571.1-93', name: 'Электроустановки зданий. Основные положения', type: 'GOST', scope: 'Электроустановки зданий', category: 'shipbuilding', publishedAt: '1993' },
  { code: 'ГОСТ 22782.0-81', name: 'Электрооборудование взрывозащищённое. Общие ТУ', type: 'GOST', scope: 'Взрывозащита общие', category: 'shipbuilding', publishedAt: '1981' },
  { code: 'ГОСТ 14254-2015', name: 'Степени защиты оболочек (IP-код)', type: 'GOST', scope: 'IP-коды', category: 'shipbuilding', publishedAt: '2015' },
  { code: 'ГОСТ 12.2.007.0-75', name: 'ССБТ. Изделия электротехнические. Общие требования безопасности', type: 'GOST', scope: 'Безопасность эл. изделий', category: 'shipbuilding', publishedAt: '1975' },
  { code: 'ГОСТ 12.2.007.1-75', name: 'ССБТ. Машины электрические вращающиеся. Требования безопасности', type: 'GOST', scope: 'Эл. машины', category: 'shipbuilding', publishedAt: '1975' },
  { code: 'ГОСТ 12.2.007.2-75', name: 'ССБТ. Трансформаторы. Требования безопасности', type: 'GOST', scope: 'Трансформаторы', category: 'shipbuilding', publishedAt: '1975' },
  { code: 'ГОСТ Р МЭК 60945-2015', name: 'Судовое оборудование. Навигационное и радиосвязное. Требования безопасности', type: 'GOST', scope: 'Судовое эл. оборудование', category: 'shipbuilding', publishedAt: '2015' },
  { code: 'ГОСТ Р 50631-94', name: 'Судовое оборудование. Общие ТУ', type: 'GOST', scope: 'Судовое оборудование', category: 'shipbuilding', publishedAt: '1994' },
  { code: 'ГОСТ 24870-2013', name: 'Судовые электроприводы. Общие ТУ', type: 'GOST', scope: 'Судовые эл. приводы', category: 'shipbuilding', publishedAt: '2013' },
  { code: 'ГОСТ 32020-2013', name: 'Совместимость технических средств электромагнитная. Электроснабжение судов', type: 'GOST', scope: 'ЭМС судов', category: 'shipbuilding', publishedAt: '2013' },
  { code: 'ГОСТ Р 51330.0-99', name: 'Электрооборудование взрывозащищённое. Часть 0. Общие требования', type: 'GOST', scope: 'Взрывозащита', category: 'shipbuilding', publishedAt: '1999' },
  { code: 'ГОСТ Р 51330.10-99', name: 'Электрооборудование взрывозащищённое. Часть 11. Искробезопасная цепь', type: 'GOST', scope: 'Искробезопасность', category: 'shipbuilding', publishedAt: '1999' },
  // Безопасность и охрана труда
  { code: 'ГОСТ 12.0.003-2015', name: 'ССБТ. Опасные и вредные производственные факторы. Классификация', type: 'GOST', scope: 'Опасные факторы', category: 'shipbuilding', publishedAt: '2015' },
  { code: 'ГОСТ 12.0.004-2015', name: 'ССБТ. Организация обучения безопасности труда', type: 'GOST', scope: 'Обучение ОТ', category: 'shipbuilding', publishedAt: '2015' },
  { code: 'ГОСТ 12.1.003-2014', name: 'ССБТ. Шум. Общие требования безопасности', type: 'GOST', scope: 'Шум', category: 'shipbuilding', publishedAt: '2014' },
  { code: 'ГОСТ 12.1.004-91', name: 'ССБТ. Пожарная безопасность. Общие требования', type: 'GOST', scope: 'Пожарная безопасность', category: 'shipbuilding', publishedAt: '1991' },
  { code: 'ГОСТ 12.1.005-88', name: 'ССБТ. Общие санитарно-гигиенические требования к воздуху рабочей зоны', type: 'GOST', scope: 'Воздух рабочей зоны', category: 'shipbuilding', publishedAt: '1988' },
  { code: 'ГОСТ 12.1.007-76', name: 'ССБТ. Вредные вещества. Классификация', type: 'GOST', scope: 'Вредные вещества', category: 'shipbuilding', publishedAt: '1976' },
  { code: 'ГОСТ 12.1.012-2004', name: 'ССБТ. Вибрационная безопасность. Общие требования', type: 'GOST', scope: 'Вибрация', category: 'shipbuilding', publishedAt: '2004' },
  { code: 'ГОСТ 12.1.029-80', name: 'ССБТ. Средства защиты от шума. Классификация', type: 'GOST', scope: 'Защита от шума', category: 'shipbuilding', publishedAt: '1980' },
  { code: 'ГОСТ 12.1.044-89', name: 'ССБТ. Пожаровзрывоопасность веществ и материалов', type: 'GOST', scope: 'Пожаровзрывоопасность', category: 'shipbuilding', publishedAt: '1989' },
  { code: 'ГОСТ 12.2.003-91', name: 'ССБТ. Оборудование производственное. Общие требования безопасности', type: 'GOST', scope: 'Оборудование ТБ', category: 'shipbuilding', publishedAt: '1991' },
  { code: 'ГОСТ 12.2.061-81', name: 'ССБТ. Оборудование. Общие требования к рабочим местам', type: 'GOST', scope: 'Рабочие места', category: 'shipbuilding', publishedAt: '1981' },
  { code: 'ГОСТ 12.3.002-2014', name: 'ССБТ. Процессы производственные. Общие требования безопасности', type: 'GOST', scope: 'Процессы ТБ', category: 'shipbuilding', publishedAt: '2014' },
  { code: 'ГОСТ 12.3.003-86', name: 'ССБТ. Работы электросварочные. Требования безопасности', type: 'GOST', scope: 'Электросварка ТБ', category: 'shipbuilding', publishedAt: '1986' },
  { code: 'ГОСТ 12.3.004-75', name: 'ССБТ. Термическая обработка металлов. Требования безопасности', type: 'GOST', scope: 'Термообработка ТБ', category: 'shipbuilding', publishedAt: '1975' },
  { code: 'ГОСТ 12.3.009-76', name: 'ССБТ. Работы погрузочно-разгрузочные. Требования безопасности', type: 'GOST', scope: 'Погрузка ТБ', category: 'shipbuilding', publishedAt: '1976' },
  { code: 'ГОСТ 12.3.020-80', name: 'ССБТ. Процессы перемещения грузов. Требования безопасности', type: 'GOST', scope: 'Перемещение ТБ', category: 'shipbuilding', publishedAt: '1980' },
  { code: 'ГОСТ 12.4.010-75', name: 'ССБТ. Средства индивидуальной защиты. Общие требования', type: 'GOST', scope: 'СИЗ', category: 'shipbuilding', publishedAt: '1975' },
  { code: 'ГОСТ 12.4.011-89', name: 'ССБТ. Средства защиты работающих. Общие требования', type: 'GOST', scope: 'СИЗ общие', category: 'shipbuilding', publishedAt: '1989' },
  { code: 'ГОСТ 12.4.023-84', name: 'ССБТ. Щитки защитные лицевые. Общие ТУ', type: 'GOST', scope: 'Щитки лицевые', category: 'shipbuilding', publishedAt: '1984' },
  { code: 'ГОСТ 12.4.084-80', name: 'ССБТ. Рукавицы специальные. ТУ', type: 'GOST', scope: 'Рукавицы', category: 'shipbuilding', publishedAt: '1980' },
  { code: 'ГОСТ 12.4.100-80', name: 'ССБТ. Рукавицы. Технические условия', type: 'GOST', scope: 'Рукавицы ТУ', category: 'shipbuilding', publishedAt: '1980' },
  { code: 'ГОСТ 12.4.103-83', name: 'ССБТ. Одежда специальная. Маркировка', type: 'GOST', scope: 'Спецодежда', category: 'shipbuilding', publishedAt: '1983' },
  { code: 'ГОСТ 12.4.121-2015', name: 'ССБТ. Противогазы промышленные. ТУ', type: 'GOST', scope: 'Противогазы', category: 'shipbuilding', publishedAt: '2015' },
  // Системы качества
  { code: 'ГОСТ Р ИСО 9001-2015', name: 'Системы менеджмента качества. Требования', type: 'GOST', scope: 'ИСО 9001', category: 'sto', publishedAt: '2015' },
  { code: 'ГОСТ Р ИСО 9000-2015', name: 'Системы менеджмента качества. Основные положения и словарь', type: 'GOST', scope: 'ИСО 9000', category: 'sto', publishedAt: '2015' },
  { code: 'ГОСТ Р ИСО 14001-2016', name: 'Системы экологического менеджмента. Требования', type: 'GOST', scope: 'ИСО 14001', category: 'sto', publishedAt: '2016' },
  { code: 'ГОСТ Р 51897-2011', name: 'Менеджмент риска. Термины и определения', type: 'GOST', scope: 'Риск-менеджмент', category: 'sto', publishedAt: '2011' },
  { code: 'ГОСТ Р ИСО 31000-2010', name: 'Менеджмент риска. Принципы и руководство', type: 'GOST', scope: 'ИСО 31000', category: 'sto', publishedAt: '2010' },
  { code: 'ГОСТ Р 51814.1-2004', name: 'Системы качества в автомобилестроении. Оценка систем качества', type: 'GOST', scope: 'QS-9000', category: 'sto', publishedAt: '2004' },
  // Метрология
  { code: 'ГОСТ 8.009-84', name: 'ГСИ. Нормируемые метрологические характеристики средств измерений', type: 'GOST', scope: 'Метрология', category: 'tolerances', publishedAt: '1984' },
  { code: 'ГОСТ 8.050-73', name: 'ГСИ. Нормальные условия выполнения линейных и угловых измерений', type: 'GOST', scope: 'Условия измерений', category: 'tolerances', publishedAt: '1973' },
  { code: 'ГОСТ 8.051-81', name: 'ГСИ. Погрешности измерения линейных размеров до 500 мм', type: 'GOST', scope: 'Погрешности измерений', category: 'tolerances', publishedAt: '1981' },
  { code: 'ГОСТ 8.113-85', name: 'ГСИ. Штангенциркули. Методы поверки', type: 'GOST', scope: 'Штангенциркули', category: 'tolerances', publishedAt: '1985' },
  { code: 'ГОСТ 166-89', name: 'Штангенциркули. ТУ', type: 'GOST', scope: 'Штангенциркули ТУ', category: 'tolerances', publishedAt: '1989' },
  { code: 'ГОСТ 4381-87', name: 'Микрометры. ТУ', type: 'GOST', scope: 'Микрометры', category: 'tolerances', publishedAt: '1987' },
  { code: 'ГОСТ 6507-90', name: 'Микрометры. Технические условия', type: 'GOST', scope: 'Микрометры ТУ', category: 'tolerances', publishedAt: '1990' },
  { code: 'ГОСТ 577-68', name: 'Индикаторы часового типа с ценой деления 0,01 мм. ТУ', type: 'GOST', scope: 'Индикаторы', category: 'tolerances', publishedAt: '1968' },
  { code: 'ГОСТ 11098-75', name: 'Скобы с отсчётным устройством. ТУ', type: 'GOST', scope: 'Скобы', category: 'tolerances', publishedAt: '1975' },
  { code: 'ГОСТ 2196-76', name: 'Концевые меры длины. ТУ', type: 'GOST', scope: 'КМД', category: 'tolerances', publishedAt: '1976' },
  { code: 'ГОСТ 9038-83', name: 'Меры длины концевые плоскопараллельные. ТУ', type: 'GOST', scope: 'Концевые меры', category: 'tolerances', publishedAt: '1983' },
  // Дополнительные материалы
  { code: 'ГОСТ 19904-90', name: 'Прокат листовой холоднокатаный. Сортамент', type: 'GOST', scope: 'Холоднокатаный лист', category: 'materials', publishedAt: '1990' },
  { code: 'ГОСТ 16523-97', name: 'Прокат тонколистовой из углеродистой стали качественной', type: 'GOST', scope: 'Тонколистовой прокат', category: 'materials', publishedAt: '1997' },
  { code: 'ГОСТ 16523-89', name: 'Прокат тонколистовой из углеродистой стали обыкновенного качества', type: 'GOST', scope: 'Тонколистовой (общего)', category: 'materials', publishedAt: '1989' },
  { code: 'ГОСТ 4041-2017', name: 'Прокат листовой холоднокатаный. ТУ', type: 'GOST', scope: 'Холоднокатаный ТУ', category: 'materials', publishedAt: '2017' },
  { code: 'ГОСТ 9045-93', name: 'Прокат тонколистовой холоднокатаный из низкоуглеродистой стали', type: 'GOST', scope: 'Тонколистовой низкоугл.', category: 'materials', publishedAt: '1993' },
  { code: 'ГОСТ 17066-94', name: 'Прокат тонколистовой из стали повышенной прочности', type: 'GOST', scope: 'Тонколистовой пов. прочн.', category: 'materials', publishedAt: '1994' },
  { code: 'ГОСТ 5582-75', name: 'Прокат тонколистовой коррозионно-стойкий, жаростойкий и жаропрочный', type: 'GOST', scope: 'Нержавеющий лист', category: 'materials', publishedAt: '1975' },
  { code: 'ГОСТ 7350-2007', name: 'Прокат листовой из коррозионно-стойкой, жаростойкой и жаропрочной стали. ТУ', type: 'GOST', scope: 'Нержавеющий лист ТУ', category: 'materials', publishedAt: '2007' },
  { code: 'ГОСТ 4784-97', name: 'Алюминий и сплавы алюминиевые деформируемые. Марки', type: 'GOST', scope: 'Алюм. сплавы', category: 'materials', publishedAt: '1997' },
  { code: 'ГОСТ 14838-78', name: 'Проволока из алюминия и алюминиевых сплавов. ТУ', type: 'GOST', scope: 'Алюм. проволока', category: 'materials', publishedAt: '1978' },
  { code: 'ГОСТ 7871-75', name: 'Проволока сварочная из алюминия и алюминиевых сплавов. ТУ', type: 'GOST', scope: 'Сварочная проволока', category: 'materials', publishedAt: '1975' },
  { code: 'ГОСТ 2246-70', name: 'Проволока стальная сварочная. ТУ', type: 'GOST', scope: 'Сварочная стальная проволока', category: 'welding', publishedAt: '1970' },
  { code: 'ГОСТ 26271-84', name: 'Проволока порошковая для дуговой сварки. ТУ', type: 'GOST', scope: 'Порошковая проволока', category: 'welding', publishedAt: '1984' },
  { code: 'ГОСТ 9087-81', name: 'Флюсы сварочные плавленые. ТУ', type: 'GOST', scope: 'Сварочные флюсы', category: 'welding', publishedAt: '1981' },
  { code: 'ГОСТ Р 52222-2004', name: 'Флюсы сварочные плавленые для дуговой сварки. ТУ', type: 'GOST', scope: 'Флюсы (новый)', category: 'welding', publishedAt: '2004' },
  { code: 'ГОСТ 21448-75', name: 'Порошковые флюсы для сварки. ТУ', type: 'GOST', scope: 'Порошковые флюсы', category: 'welding', publishedAt: '1975' },
  { code: 'ГОСТ 9466-75', name: 'Электроды покрытые металлические для ручной дуговой сварки. Классификация', type: 'GOST', scope: 'Электроды классификация', category: 'welding', publishedAt: '1975' },
  { code: 'ГОСТ 9467-75', name: 'Электроды покрытые металлические для ручной дуговой сварки. Типы', type: 'GOST', scope: 'Электроды типы', category: 'welding', publishedAt: '1975' },
  { code: 'ГОСТ 10052-75', name: 'Электроды покрытые для сварки высоколегированных сталей. Типы', type: 'GOST', scope: 'Электроды высоколегир.', category: 'welding', publishedAt: '1975' },
  { code: 'ГОСТ 977-88', name: 'Отливки стальные. Общие ТУ', type: 'GOST', scope: 'Стальные отливки', category: 'materials', publishedAt: '1988' },
  { code: 'ГОСТ 26358-84', name: 'Отливки из чугуна. Общие ТУ', type: 'GOST', scope: 'Чугунные отливки', category: 'materials', publishedAt: '1984' },
  { code: 'ГОСТ 1412-85', name: 'Чугун с пластинчатым графитом. Марки', type: 'GOST', scope: 'Серый чугун', category: 'materials', publishedAt: '1985' },
  { code: 'ГОСТ 7293-85', name: 'Чугун с шаровидным графитом. Марки', type: 'GOST', scope: 'ВЧШГ', category: 'materials', publishedAt: '1985' },
  { code: 'ГОСТ 1215-79', name: 'Отливки из ковкого чугуна. Марки', type: 'GOST', scope: 'Ковкий чугун', category: 'materials', publishedAt: '1979' },
  { code: 'ГОСТ 1583-93', name: 'Сплавы алюминиевые литейные. Марки', type: 'GOST', scope: 'Литейные алюм. сплавы', category: 'materials', publishedAt: '1993' },
]

// ============ ДОПОЛНИТЕЛЬНЫЕ ПРАВИЛА (200+) ============
// Расширяем по категориям: штамп (детализация), материалы (справочники), сварка, геометрия, CAD, семантика
const MORE_RULES = [
  // Штамп — детализация (R-STAMP-006..030)
  { code: 'R-STAMP-006', name: 'Обозначение без точки в конце', description: 'Обозначение не должно заканчиваться точкой', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Обозначение', standardCode: 'ГОСТ 2.201-80' },
  { code: 'R-STAMP-007', name: 'Обозначение без пробелов', description: 'В обозначении не допускаются пробелы', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Обозначение', standardCode: 'ГОСТ 2.201-80' },
  { code: 'R-STAMP-008', name: 'Наименование без кавычек', description: 'Наименование изделия не заключается в кавычки', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Наименование', standardCode: 'ГОСТ 2.109-73' },
  { code: 'R-STAMP-009', name: 'Наименование без ГОСТ в поле', description: 'В поле наименования не должно быть ссылок на ГОСТ', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Наименование', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-STAMP-010', name: 'Наименование одним существительным', description: 'Наименование должно начинаться с существительного', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Наименование', standardCode: 'ГОСТ 2.109-73' },
  { code: 'R-STAMP-011', name: 'Масштаб в формате N:M', description: 'Масштаб должен быть записан через двоеточие', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Масштаб', standardCode: 'ГОСТ 2.302-68' },
  { code: 'R-STAMP-012', name: 'Масштаб без пробелов', description: 'В записи масштаба не допускаются пробелы', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Масштаб', standardCode: 'ГОСТ 2.302-68' },
  { code: 'R-STAMP-013', name: 'Масса числом', description: 'Масса должна быть числом с единицей измерения', category: 'stamp', method: 'deterministic', severity: 'medium', gostField: 'Масса', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-STAMP-014', name: 'Масса с запятой', description: 'Десятичный разделитель в массе — запятая', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Масса', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-STAMP-015', name: 'Масса до 3 знаков', description: 'Масса указывается не более чем с 3 значащими знаками', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Масса', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-STAMP-016', name: 'Материал без переноса строки', description: 'В обозначении материала не должно быть переносов', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Материал', standardCode: 'ГОСТ 2.109-73' },
  { code: 'R-STAMP-017', name: 'Материал заглавными буквами', description: 'Обозначение материала пишется заглавными буквами', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Материал', standardCode: 'ГОСТ 2.109-73' },
  { code: 'R-STAMP-018', name: 'Литера заглавная', description: 'Литера указывается заглавной буквой', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Литера', standardCode: 'ГОСТ 2.103-2013' },
  { code: 'R-STAMP-019', name: 'Стадия заглавными', description: 'Стадия указывается заглавными буквами', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Стадия', standardCode: 'ГОСТ 2.103-2013' },
  { code: 'R-STAMP-020', name: 'Подпись без инициалов', description: 'В графе подписи должны быть фамилия и инициалы', category: 'stamp', method: 'deterministic', severity: 'medium', gostField: 'Подписи', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-STAMP-021', name: 'Дата в формате ДД.ММ.ГГГГ', description: 'Дата должна быть в формате ДД.ММ.ГГГГ', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Даты', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-STAMP-022', name: 'Дата реалистичная', description: 'Дата не должна быть в будущем или слишком старой', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Даты', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-STAMP-023', name: 'Формат заглавными', description: 'Формат указывается заглавной буквой (A0-A4)', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Формат', standardCode: 'ГОСТ 2.301-68' },
  { code: 'R-STAMP-024', name: 'Формат с буквой A латиницей', description: 'Буква формата — латинская A', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Формат', standardCode: 'ГОСТ 2.301-68' },
  { code: 'R-STAMP-025', name: 'Инвентарный номер указан', description: 'Для архивных документов инв.номер обязателен', category: 'stamp', method: 'deterministic', severity: 'medium', gostField: 'Инв.номер', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-STAMP-026', name: 'Количество листов указано', description: 'Для многостраничных документов количество листов обязательно', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Листов', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-STAMP-027', name: 'Лист указан', description: 'Номер текущего листа указан', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Лист', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-STAMP-028', name: 'Листов ≥ Лист', description: 'Общее количество листов не меньше текущего номера', category: 'stamp', method: 'deterministic', severity: 'medium', gostField: 'Лист/Листов', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-STAMP-029', name: 'Подпись Н.контр. с датой', description: 'Графа Н.контр. должна содержать дату', category: 'stamp', method: 'deterministic', severity: 'medium', gostField: 'Подписи/Даты', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-STAMP-030', name: 'Подпись Утв. с датой', description: 'Графа Утв. должна содержать дату', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Подписи/Даты', standardCode: 'ГОСТ 2.104-2006' },
  // Материалы — справочники (R-MAT-006..040)
  { code: 'R-MAT-006', name: 'Сталь 09Г2С в перечне', description: 'При указании стали 09Г2С ГОСТ 19281 должен быть в перечне', category: 'material', method: 'deterministic', severity: 'high', gostField: 'Материал', standardCode: 'ГОСТ 19281-2014' },
  { code: 'R-MAT-007', name: 'Сталь 10ХСНД в перечне', description: 'При указании стали 10ХСНД ГОСТ 19281 должен быть в перечне', category: 'material', method: 'deterministic', severity: 'high', gostField: 'Материал', standardCode: 'ГОСТ 19281-2014' },
  { code: 'R-MAT-008', name: 'Сталь Ст3сп в перечне', description: 'При указании Ст3сп ГОСТ 380 должен быть в перечне', category: 'material', method: 'deterministic', severity: 'high', gostField: 'Материал', standardCode: 'ГОСТ 380-2005' },
  { code: 'R-MAT-009', name: 'Сталь 20 в перечне', description: 'При указании стали 20 ГОСТ 1050 должен быть в перечне', category: 'material', method: 'deterministic', severity: 'high', gostField: 'Материал', standardCode: 'ГОСТ 1050-2013' },
  { code: 'R-MAT-010', name: 'Сталь 09Г2 в перечне', description: 'При указании стали 09Г2 ГОСТ 19281 должен быть в перечне', category: 'material', method: 'deterministic', severity: 'high', gostField: 'Материал', standardCode: 'ГОСТ 19281-2014' },
  { code: 'R-MAT-011', name: 'Бронза БрАЖ9-4 в перечне', description: 'При указании бронзы БрАЖ9-4 ГОСТ 18175 должен быть в перечне', category: 'material', method: 'deterministic', severity: 'medium', gostField: 'Материал', standardCode: 'ГОСТ 18175-78' },
  { code: 'R-MAT-012', name: 'Латунь Л63 в перечне', description: 'При указании латуни Л63 ГОСТ 15527 должен быть в перечне', category: 'material', method: 'deterministic', severity: 'medium', gostField: 'Материал', standardCode: 'ГОСТ 15527-2004' },
  { code: 'R-MAT-013', name: 'Алюминий АМг6 в перечне', description: 'При указании АМг6 ГОСТ 4784 должен быть в перечне', category: 'material', method: 'deterministic', severity: 'medium', gostField: 'Материал', standardCode: 'ГОСТ 4784-97' },
  { code: 'R-MAT-014', name: 'Сталь категории судостроения', description: 'Сталь должна быть судостроительной категории (A, B, D, E)', category: 'material', method: 'semantic', severity: 'high', gostField: 'Материал', standardCode: 'Регистр. ПКС. Часть II «Корпус»' },
  { code: 'R-MAT-015', name: 'Сталь с указанием категории', description: 'Для судостроения должна быть указана категория стали', category: 'material', method: 'semantic', severity: 'medium', gostField: 'Материал', standardCode: 'Регистр. ПКС. Часть II «Корпус»' },
  { code: 'R-MAT-016', name: 'Сталь с испытанием на ударную вязкость', description: 'Для ответственных конструкций — испытание на ударную вязкость', category: 'material', method: 'semantic', severity: 'medium', gostField: 'Материал', standardCode: 'ГОСТ 19281-2014' },
  { code: 'R-MAT-017', name: 'Сталь с указанием толщины', description: 'Для листового проката должна быть указана толщина', category: 'material', method: 'semantic', severity: 'low', gostField: 'Материал', standardCode: 'ГОСТ 19903-2015' },
  { code: 'R-MAT-018', name: 'Материал для северного исполнения', description: 'Для северного исполнения — сталь 09Г2С не ниже 14 категории', category: 'material', method: 'semantic', severity: 'high', gostField: 'Материал', standardCode: 'ГОСТ 19281-2014' },
  { code: 'R-MAT-019', name: 'Нержавеющая сталь с ГОСТ 5632', description: 'Нержавеющие стали должны ссылаться на ГОСТ 5632', category: 'material', method: 'deterministic', severity: 'medium', gostField: 'Материал', standardCode: 'ГОСТ 5632-2014' },
  { code: 'R-MAT-020', name: 'Цветной металл с ГОСТ на марку', description: 'Цветные металлы должны иметь ссылку на ГОСТ марки', category: 'material', method: 'deterministic', severity: 'medium', gostField: 'Материал', standardCode: 'ГОСТ 4784-97' },
  { code: 'R-MAT-021', name: 'Полимер с обозначением', description: 'Полимерные материалы должны иметь полное обозначение', category: 'material', method: 'semantic', severity: 'low', gostField: 'Материал', standardCode: 'ГОСТ 12423-66' },
  { code: 'R-MAT-022', name: 'Резина с твёрдостью', description: 'Резиновые уплотнения должны иметь указание твёрдости', category: 'material', method: 'semantic', severity: 'low', gostField: 'Материал', standardCode: 'ГОСТ 12855-77' },
  { code: 'R-MAT-023', name: 'Кольцо уплотнительное с ГОСТ 9833', description: 'Уплотнительные кольца должны ссылаться на ГОСТ 9833', category: 'material', method: 'deterministic', severity: 'medium', gostField: 'Материал', standardCode: 'ГОСТ 9833-73' },
  { code: 'R-MAT-024', name: 'Покрытие указано', description: 'Для металлических деталей должно быть указано покрытие', category: 'material', method: 'semantic', severity: 'medium', gostField: 'Покрытие', standardCode: 'ГОСТ 9.032-74' },
  { code: 'R-MAT-025', name: 'Покрытие с ГОСТ', description: 'Обозначение покрытия должно содержать ГОСТ', category: 'material', method: 'deterministic', severity: 'low', gostField: 'Покрытие', standardCode: 'ГОСТ 9.032-74' },
  { code: 'R-MAT-026', name: 'Грунт в ТТ', description: 'При наличии покрытия в ТТ должен быть указан грунт', category: 'material', method: 'semantic', severity: 'low', gostField: 'Покрытие', standardCode: 'ГОСТ 9.032-74' },
  { code: 'R-MAT-027', name: 'Эмаль в ТТ', description: 'При наличии покрытия в ТТ должна быть указана эмаль', category: 'material', method: 'semantic', severity: 'low', gostField: 'Покрытие', standardCode: 'ГОСТ 9.032-74' },
  { code: 'R-MAT-028', name: 'Цвет покрытия указан', description: 'Цвет покрытия должен быть указан по каталогу RAL', category: 'material', method: 'semantic', severity: 'low', gostField: 'Покрытие', standardCode: 'ГОСТ 9.032-74' },
  { code: 'R-MAT-029', name: 'Толщина покрытия', description: 'Должна быть указана толщина покрытия в мкм', category: 'material', method: 'semantic', severity: 'low', gostField: 'Покрытие', standardCode: 'ГОСТ 9.407-2015' },
  { code: 'R-MAT-030', name: 'Климатическое исполнение в ТТ', description: 'Для судового — указание климатического исполнения У/УХЛ/М', category: 'material', method: 'semantic', severity: 'medium', gostField: 'Климат', standardCode: 'ГОСТ 15150-69' },
  { code: 'R-MAT-031', name: 'Категория размещения', description: 'Должна быть указана категория размещения (1-5)', category: 'material', method: 'semantic', severity: 'low', gostField: 'Климат', standardCode: 'ГОСТ 15150-69' },
  { code: 'R-MAT-032', name: 'Сталь для сварной конструкции', description: 'Сталь должна быть пригодна для сварных конструкций', category: 'material', method: 'semantic', severity: 'medium', gostField: 'Материал', standardCode: 'ГОСТ 19281-2014' },
  { code: 'R-MAT-033', name: 'Сталь с сертификацией Регистра', description: 'Для судостроения — сталь должна иметь сертификат Регистра', category: 'material', method: 'semantic', severity: 'high', gostField: 'Материал', standardCode: 'Регистр. ПКС. Часть II «Корпус»' },
  { code: 'R-MAT-034', name: 'Листовой прокат с указанием размера', description: 'Листовой прокат должен иметь указание толщины и габаритов', category: 'material', method: 'semantic', severity: 'low', gostField: 'Материал', standardCode: 'ГОСТ 19903-2015' },
  { code: 'R-MAT-035', name: 'Сортовой прокат с указанием размера', description: 'Сортовой прокат должен иметь указание размера сечения', category: 'material', method: 'semantic', severity: 'low', gostField: 'Материал', standardCode: 'ГОСТ 2590-2006' },
  { code: 'R-MAT-036', name: 'Уголок с указанием размера', description: 'Уголок должен иметь указание номера и толщины полки', category: 'material', method: 'semantic', severity: 'low', gostField: 'Материал', standardCode: 'ГОСТ 8509-93' },
  { code: 'R-MAT-037', name: 'Швеллер с указанием номера', description: 'Швеллер должен иметь указание номера', category: 'material', method: 'semantic', severity: 'low', gostField: 'Материал', standardCode: 'ГОСТ 8240-97' },
  { code: 'R-MAT-038', name: 'Двутавр с указанием номера', description: 'Двутавр должен иметь указание номера', category: 'material', method: 'semantic', severity: 'low', gostField: 'Материал', standardCode: 'ГОСТ 8239-89' },
  { code: 'R-MAT-039', name: 'Труба с указанием диаметра и толщины', description: 'Труба должна иметь указание наружного диаметра и толщины стенки', category: 'material', method: 'semantic', severity: 'medium', gostField: 'Материал', standardCode: 'ГОСТ 8732-78' },
  { code: 'R-MAT-040', name: 'Крепёж с классом прочности', description: 'Крепёжные детали должны иметь указание класса прочности', category: 'material', method: 'semantic', severity: 'medium', gostField: 'Крепёж', standardCode: 'ГОСТ 1759.4-87' },
  // Сварка (R-WELD-006..030)
  { code: 'R-WELD-006', name: 'Сварной шов с ГОСТ на метод', description: 'Должен быть указан ГОСТ на метод сварки (5264, 14771, 8713)', category: 'welding', method: 'semantic', severity: 'high', gostField: 'Сварка', standardCode: 'ГОСТ 2.312-72' },
  { code: 'R-WELD-007', name: 'Указан тип шва', description: 'Должен быть указан тип сварного шва (стыковой/угловой/тавровый)', category: 'welding', method: 'vision', severity: 'medium', gostField: 'Сварка', standardCode: 'ГОСТ 5264-80' },
  { code: 'R-WELD-008', name: 'Катет углового шва в пределах', description: 'Катет углового шва должен быть в диапазоне 3-20 мм', category: 'welding', method: 'vision', severity: 'medium', gostField: 'Сварка', standardCode: 'ГОСТ 5264-80' },
  { code: 'R-WELD-009', name: 'Длина шва указана', description: 'Для прерывистых швов должна быть указана длина', category: 'welding', method: 'vision', severity: 'medium', gostField: 'Сварка', standardCode: 'ГОСТ 2.312-72' },
  { code: 'R-WELD-010', name: 'Шаг прерывистого шва', description: 'Для прерывистых швов должен быть указан шаг', category: 'welding', method: 'vision', severity: 'medium', gostField: 'Сварка', standardCode: 'ГОСТ 2.312-72' },
  { code: 'R-WELD-011', name: 'Обозначение шва по ГОСТ 2.312', description: 'Структура обозначения сварного шва', category: 'welding', method: 'vision', severity: 'high', gostField: 'Сварка', standardCode: 'ГОСТ 2.312-72' },
  { code: 'R-WELD-012', name: 'Стрелка указывает на шов', description: 'Стрелка выноски должна указывать на шов', category: 'welding', method: 'vision', severity: 'medium', gostField: 'Сварка', standardCode: 'ГОСТ 2.312-72' },
  { code: 'R-WELD-013', name: 'Односторонний/двусторонний шов', description: 'Должно быть указано односторонний или двусторонний шов', category: 'welding', method: 'vision', severity: 'low', gostField: 'Сварка', standardCode: 'ГОСТ 2.312-72' },
  { code: 'R-WELD-014', name: 'Снятие усиления шва', description: 'При необходимости — указание о снятии усиления', category: 'welding', method: 'vision', severity: 'low', gostField: 'Сварка', standardCode: 'ГОСТ 2.312-72' },
  { code: 'R-WELD-015', name: 'Подготовка кромок', description: 'Должна быть указана подготовка кромок под сварку', category: 'welding', method: 'vision', severity: 'medium', gostField: 'Сварка', standardCode: 'ГОСТ 5264-80' },
  { code: 'R-WELD-016', name: 'Контроль ВИК', description: 'Для ответственных швов — визуально-измерительный контроль', category: 'welding', method: 'semantic', severity: 'high', gostField: 'Сварка', standardCode: 'ГОСТ Р ИСО 17635-2015' },
  { code: 'R-WELD-017', name: 'Контроль УЗК', description: 'Для ответственных швов — ультразвуковой контроль', category: 'welding', method: 'semantic', severity: 'medium', gostField: 'Сварка', standardCode: 'ГОСТ Р ИСО 17640-2017' },
  { code: 'R-WELD-018', name: 'Контроль радиографический', description: 'Для ответственных швов — радиографический контроль', category: 'welding', method: 'semantic', severity: 'medium', gostField: 'Сварка', standardCode: 'ГОСТ Р ИСО 17636-1-2017' },
  { code: 'R-WELD-019', name: 'Контроль магнитопорошковый', description: 'Для поверхностных дефектов — магнитопорошковый контроль', category: 'welding', method: 'semantic', severity: 'low', gostField: 'Сварка', standardCode: 'ГОСТ Р 57181-2016' },
  { code: 'R-WELD-020', name: 'Контроль капиллярный', description: 'Для поверхностных дефектов — капиллярный контроль', category: 'welding', method: 'semantic', severity: 'low', gostField: 'Сварка', standardCode: 'ГОСТ Р 57182-2016' },
  { code: 'R-WELD-021', name: 'Тип сварного соединения', description: 'Тип соединения (С1-С40, У1-У10, Т1-Т9)', category: 'welding', method: 'vision', severity: 'medium', gostField: 'Сварка', standardCode: 'ГОСТ 5264-80' },
  { code: 'R-WELD-022', name: 'Сварочные материалы в ТТ', description: 'В ТТ должны быть указаны сварочные материалы', category: 'welding', method: 'semantic', severity: 'medium', gostField: 'Сварка', standardCode: 'ГОСТ 2246-70' },
  { code: 'R-WELD-023', name: 'Марка электрода', description: 'Должна быть указана марка электрода/проволоки', category: 'welding', method: 'semantic', severity: 'low', gostField: 'Сварка', standardCode: 'ГОСТ 9466-75' },
  { code: 'R-WELD-024', name: 'Термообработка шва', description: 'При необходимости — указание термообработки шва', category: 'welding', method: 'semantic', severity: 'medium', gostField: 'Сварка', standardCode: 'ГОСТ 2.312-72' },
  { code: 'R-WELD-025', name: 'Катет шва для таврового соединения', description: 'Катет таврового шва должен быть указан', category: 'welding', method: 'vision', severity: 'medium', gostField: 'Сварка', standardCode: 'ГОСТ 5264-80' },
  { code: 'R-WELD-026', name: 'Шов непрерывный/прерывистый', description: 'Должен быть указан характер шва', category: 'welding', method: 'vision', severity: 'low', gostField: 'Сварка', standardCode: 'ГОСТ 2.312-72' },
  { code: 'R-WELD-027', name: 'Шов по замкнутому контуру', description: 'Должен быть указан контур шва (замкнутый/незамкнутый)', category: 'welding', method: 'vision', severity: 'low', gostField: 'Сварка', standardCode: 'ГОСТ 2.312-72' },
  { code: 'R-WELD-028', name: 'Монтажный шов', description: 'Монтажные швы должны быть отмечены', category: 'welding', method: 'vision', severity: 'medium', gostField: 'Сварка', standardCode: 'ГОСТ 2.312-72' },
  { code: 'R-WELD-029', name: 'Подварка корня шва', description: 'При необходимости — указание подварки корня', category: 'welding', method: 'semantic', severity: 'low', gostField: 'Сварка', standardCode: 'ГОСТ 2.312-72' },
  { code: 'R-WELD-030', name: 'Сварка в защитном газе', description: 'При сварке в защитном газе — указать тип газа', category: 'welding', method: 'semantic', severity: 'medium', gostField: 'Сварка', standardCode: 'ГОСТ 14771-76' },
  // Геометрия и виды (R-VIEW-004..025)
  { code: 'R-VIEW-004', name: 'Главный вид в проекции', description: 'Главный вид должен быть на месте проекции', category: 'geometry', method: 'vision', severity: 'medium', gostField: 'Геометрия', standardCode: 'ГОСТ 2.305-2008' },
  { code: 'R-VIEW-005', name: 'Виды обозначены буквами', description: 'Дополнительные виды обозначаются буквами (А, Б, В)', category: 'geometry', method: 'vision', severity: 'low', gostField: 'Геометрия', standardCode: 'ГОСТ 2.305-2008' },
  { code: 'R-VIEW-006', name: 'Стрелка направления вида', description: 'Направление взгляда указывается стрелкой', category: 'geometry', method: 'vision', severity: 'medium', gostField: 'Геометрия', standardCode: 'ГОСТ 2.305-2008' },
  { code: 'R-VIEW-007', name: 'Разрез обозначен', description: 'Разрез обозначается буквами (А-А)', category: 'geometry', method: 'vision', severity: 'medium', gostField: 'Геометрия', standardCode: 'ГОСТ 2.305-2008' },
  { code: 'R-VIEW-008', name: 'Сечение обозначено', description: 'Сечение обозначается буквами', category: 'geometry', method: 'vision', severity: 'low', gostField: 'Геометрия', standardCode: 'ГОСТ 2.305-2008' },
  { code: 'R-VIEW-009', name: 'Количество размеров', description: 'Каждый элемент должен иметь достаточное количество размеров', category: 'geometry', method: 'vision', severity: 'high', gostField: 'Размеры', standardCode: 'ГОСТ 2.307-2011' },
  { code: 'R-VIEW-010', name: 'Размеры от базы', description: 'Размеры должны проставляться от конструкторской базы', category: 'geometry', method: 'vision', severity: 'medium', gostField: 'Размеры', standardCode: 'ГОСТ 2.307-2011' },
  { code: 'R-VIEW-011', name: 'Неуказанные радиусы', description: 'Неуказанные радиусы скруглений должны быть в ТТ', category: 'geometry', method: 'semantic', severity: 'low', gostField: 'Размеры', standardCode: 'ГОСТ 2.307-2011' },
  { code: 'R-VIEW-012', name: 'Размеры наружные/внутренние', description: 'Наружные и внутренние размеры не должны пересекаться', category: 'geometry', method: 'vision', severity: 'low', gostField: 'Размеры', standardCode: 'ГОСТ 2.307-2011' },
  { code: 'R-VIEW-013', name: 'Размерные линии', description: 'Размерные линии должны быть параллельны', category: 'geometry', method: 'vision', severity: 'low', gostField: 'Размеры', standardCode: 'ГОСТ 2.307-2011' },
  { code: 'R-VIEW-014', name: 'Выносные линии', description: 'Выносные линии должны выходить за размерные', category: 'geometry', method: 'vision', severity: 'low', gostField: 'Размеры', standardCode: 'ГОСТ 2.307-2011' },
  { code: 'R-VIEW-015', name: 'Стрелки размеров', description: 'Стрелки размеров должны быть стандартными', category: 'geometry', method: 'vision', severity: 'low', gostField: 'Размеры', standardCode: 'ГОСТ 2.307-2011' },
  { code: 'R-VIEW-016', name: 'Размеры не закрывают линии', description: 'Размерные числа не должны пересекать линии', category: 'geometry', method: 'vision', severity: 'low', gostField: 'Размеры', standardCode: 'ГОСТ 2.307-2011' },
  { code: 'R-VIEW-017', name: 'Допуски формы', description: 'Допуски формы должны быть указаны для ответственных поверхностей', category: 'geometry', method: 'vision', severity: 'medium', gostField: 'Допуски', standardCode: 'ГОСТ 2.308-2011' },
  { code: 'R-VIEW-018', name: 'Допуски расположения', description: 'Допуски расположения должны быть указаны', category: 'geometry', method: 'vision', severity: 'medium', gostField: 'Допуски', standardCode: 'ГОСТ 2.308-2011' },
  { code: 'R-VIEW-019', name: 'Символы допусков', description: 'Символы допусков должны соответствовать ГОСТ 2.308', category: 'geometry', method: 'vision', severity: 'low', gostField: 'Допуски', standardCode: 'ГОСТ 2.308-2011' },
  { code: 'R-VIEW-020', name: 'Шероховатость главной поверхности', description: 'Для главной обрабатываемой поверхности — указание шероховатости', category: 'geometry', method: 'vision', severity: 'medium', gostField: 'Шероховатость', standardCode: 'ГОСТ 2.309-73' },
  { code: 'R-VIEW-021', name: 'Шероховатость по ГОСТ', description: 'Параметры шероховатости должны быть из ГОСТ 2789', category: 'geometry', method: 'vision', severity: 'low', gostField: 'Шероховатость', standardCode: 'ГОСТ 2789-73' },
  { code: 'R-VIEW-022', name: 'Направление шероховатости', description: 'При необходимости — направление неровностей', category: 'geometry', method: 'vision', severity: 'low', gostField: 'Шероховатость', standardCode: 'ГОСТ 2.309-73' },
  { code: 'R-VIEW-023', name: 'Базы для допусков', description: 'Должны быть указаны базы для допусков расположения', category: 'geometry', method: 'vision', severity: 'medium', gostField: 'Допуски', standardCode: 'ГОСТ 2.308-2011' },
  { code: 'R-VIEW-024', name: 'Резьба обозначена', description: 'Резьба должна быть обозначена по ГОСТ 2.311', category: 'geometry', method: 'vision', severity: 'high', gostField: 'Резьба', standardCode: 'ГОСТ 2.311-68' },
  { code: 'R-VIEW-025', name: 'Длина резьбы', description: 'Длина резьбы должна быть указана', category: 'geometry', method: 'vision', severity: 'medium', gostField: 'Резьба', standardCode: 'ГОСТ 2.311-68' },
  // CAD-атрибуты (R-CAD-005..025)
  { code: 'R-CAD-005', name: 'CAD: конфигурация по умолчанию', description: 'Должна быть конфигурация по умолчанию', category: 'cad_attr', method: 'vision', severity: 'low', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-006', name: 'CAD: материал в свойствах', description: 'Свойство "Материал" должно быть заполнено', category: 'cad_attr', method: 'vision', severity: 'medium', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-007', name: 'CAD: масса в свойствах', description: 'Свойство "Масса" должно быть заполнено', category: 'cad_attr', method: 'vision', severity: 'medium', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-008', name: 'CAD: обозначение в свойствах', description: 'Свойство "Обозначение" должно быть заполнено', category: 'cad_attr', method: 'vision', severity: 'high', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-009', name: 'CAD: наименование в свойствах', description: 'Свойство "Наименование" должно быть заполнено', category: 'cad_attr', method: 'vision', severity: 'high', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-010', name: 'CAD: автор в свойствах', description: 'Свойство "Автор" должно быть заполнено', category: 'cad_attr', method: 'vision', severity: 'low', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-011', name: 'CAD: дата создания', description: 'Свойство "Дата создания" должно быть заполнено', category: 'cad_attr', method: 'vision', severity: 'low', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-012', name: 'CAD: листы чертежа', description: 'В чертеже должны быть листы', category: 'cad_attr', method: 'vision', severity: 'medium', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-013', name: 'CAD: виды на листе', description: 'На каждом листе должны быть виды', category: 'cad_attr', method: 'vision', severity: 'medium', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-014', name: 'CAD: штамп на листе', description: 'На каждом листе должна быть основная надпись', category: 'cad_attr', method: 'vision', severity: 'high', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-015', name: 'CAD: слои стандартизованы', description: 'Слои должны быть названы по СТО', category: 'cad_attr', method: 'vision', severity: 'low', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-016', name: 'CAD: масштаб вида', description: 'Масштаб каждого вида должен быть указан', category: 'cad_attr', method: 'vision', severity: 'low', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-017', name: 'CAD: формат листа', description: 'Формат листа должен быть указан в свойствах', category: 'cad_attr', method: 'vision', severity: 'medium', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-018', name: 'CAD: единицы измерения', description: 'Единицы измерения — мм', category: 'cad_attr', method: 'vision', severity: 'medium', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-019', name: 'CAD: точность', description: 'Точность модели должна соответствовать допуску', category: 'cad_attr', method: 'vision', severity: 'low', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-020', name: 'CAD: связи сборки', description: 'Связи в сборке должны быть корректными', category: 'cad_attr', method: 'vision', severity: 'medium', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-021', name: 'CAD: уникальные имена компонентов', description: 'Компоненты сборки должны иметь уникальные имена', category: 'cad_attr', method: 'vision', severity: 'low', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-022', name: 'CAD: отсутствие коллизий', description: 'В сборке не должно быть коллизий', category: 'cad_attr', method: 'vision', severity: 'medium', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-023', name: 'CAD: экспорт PDF', description: 'Должен быть подготовлен PDF для архива', category: 'cad_attr', method: 'vision', severity: 'low', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-024', name: 'CAD: экспорт STEP', description: 'Для 3D-моделей — экспорт STEP', category: 'cad_attr', method: 'vision', severity: 'low', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  { code: 'R-CAD-025', name: 'CAD: версия файла', description: 'Должна быть указана версия CAD-системы', category: 'cad_attr', method: 'vision', severity: 'low', gostField: 'CAD', standardCode: 'СТО Северо-Верфь-005-2024' },
  // Спецификации (R-SPEC-006..025)
  { code: 'R-SPEC-006', name: 'Спецификация: формат A4', description: 'Спецификация выполняется на формате A4', category: 'specification', method: 'deterministic', severity: 'medium', gostField: 'Спецификация', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SPEC-007', name: 'Спецификация: основная надпись форма 2', description: 'Основная надпись по форме 2', category: 'specification', method: 'deterministic', severity: 'medium', gostField: 'Спецификация', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-SPEC-008', name: 'Спецификация: графы заполнены', description: 'Все графы спецификации должны быть заполнены', category: 'specification', method: 'deterministic', severity: 'high', gostField: 'Спецификация', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SPEC-009', name: 'Спецификация: обозначения уникальны', description: 'Обозначения в спецификации не должны повторяться', category: 'specification', method: 'deterministic', severity: 'high', gostField: 'Спецификация', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SPEC-010', name: 'Спецификация: количество > 0', description: 'Количество позиций должно быть больше нуля', category: 'specification', method: 'deterministic', severity: 'high', gostField: 'Спецификация', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SPEC-011', name: 'Спецификация: раздел Документация', description: 'Раздел "Документация" должен быть первым', category: 'specification', method: 'semantic', severity: 'medium', gostField: 'Спецификация', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SPEC-012', name: 'Спецификация: раздел Детали', description: 'Раздел "Детали" должен присутствовать для сборочного чертежа', category: 'specification', method: 'semantic', severity: 'medium', gostField: 'Спецификация', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SPEC-013', name: 'Спецификация: раздел Стандартные изделия', description: 'Стандартные изделия в отдельном разделе', category: 'specification', method: 'semantic', severity: 'medium', gostField: 'Спецификация', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SPEC-014', name: 'Спецификация: раздел Прочие изделия', description: 'Прочие изделия в отдельном разделе', category: 'specification', method: 'semantic', severity: 'low', gostField: 'Спецификация', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SPEC-015', name: 'Спецификация: раздел Материалы', description: 'Материалы в отдельном разделе', category: 'specification', method: 'semantic', severity: 'medium', gostField: 'Спецификация', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SPEC-016', name: 'Спецификация: сортировка в разделе', description: 'Внутри раздела изделия сортируются по обозначению', category: 'specification', method: 'deterministic', severity: 'low', gostField: 'Спецификация', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SPEC-017', name: 'Спецификация: стандартные изделия по ГОСТ', description: 'Стандартные изделия должны иметь ссылку на ГОСТ', category: 'specification', method: 'deterministic', severity: 'high', gostField: 'Спецификация', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SPEC-018', name: 'Спецификация: масса сборки', description: 'В спецификации должна быть указана масса сборки', category: 'specification', method: 'deterministic', severity: 'medium', gostField: 'Спецификация', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SPEC-019', name: 'Спецификация: формат обозначения', description: 'Обозначения должны соответствовать ГОСТ 2.201', category: 'specification', method: 'deterministic', severity: 'medium', gostField: 'Спецификация', standardCode: 'ГОСТ 2.201-80' },
  { code: 'R-SPEC-020', name: 'Спецификация: листы пронумерованы', description: 'Листы спецификации должны быть пронумерованы', category: 'specification', method: 'deterministic', severity: 'low', gostField: 'Спецификация', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SPEC-021', name: 'Спецификация: ГОСТ в перечне', description: 'Все ссылочные ГОСТ должны быть в перечне', category: 'specification', method: 'deterministic', severity: 'medium', gostField: 'Спецификация', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-SPEC-022', name: 'Спецификация: позиции на чертеже', description: 'Все позиции спецификации должны быть на сборочном чертеже', category: 'specification', method: 'semantic', severity: 'high', gostField: 'Спецификация', standardCode: 'ГОСТ 2.109-73' },
  { code: 'R-SPEC-023', name: 'Спецификация: шарики позиций', description: 'Позиции должны быть в кружках', category: 'specification', method: 'vision', severity: 'medium', gostField: 'Спецификация', standardCode: 'ГОСТ 2.109-73' },
  { code: 'R-SPEC-024', name: 'Спецификация: линии-выноски', description: 'Линии-выноски не должны пересекаться', category: 'specification', method: 'vision', severity: 'low', gostField: 'Спецификация', standardCode: 'ГОСТ 2.109-73' },
  { code: 'R-SPEC-025', name: 'Спецификация: нет пустых строк', description: 'В спецификации не должно быть пустых строк', category: 'specification', method: 'deterministic', severity: 'medium', gostField: 'Спецификация', standardCode: 'ГОСТ 2.106-96' },
  // Семантические (R-SEM-008..030)
  { code: 'R-SEM-008', name: 'Обозначение чертежа и спецификации', description: 'Обозначение сборочного чертежа и спецификации должны совпадать', category: 'semantic', method: 'semantic', severity: 'high', gostField: 'Обозначение', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SEM-009', name: 'Обозначение детали и сборки', description: 'Обозначение детали должно быть подчинено обозначению сборки', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Обозначение', standardCode: 'ГОСТ 2.201-80' },
  { code: 'R-SEM-010', name: 'Масса детали и масса в спецификации', description: 'Масса детали в чертеже и в спецификации должны совпадать', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Масса', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SEM-011', name: 'Наименование детали и сборки', description: 'Наименование детали в спецификации и в чертеже должны совпадать', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Наименование', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SEM-012', name: 'Материал детали и в спецификации', description: 'Материал детали в чертеже и в спецификации должны совпадать', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Материал', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SEM-013', name: 'Количество деталей', description: 'Количество деталей в спецификации соответствует сборке', category: 'semantic', method: 'semantic', severity: 'high', gostField: 'Спецификация', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SEM-014', name: 'Габаритные размеры', description: 'Габаритные размеры должны быть указаны', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Размеры', standardCode: 'ГОСТ 2.307-2011' },
  { code: 'R-SEM-015', name: 'Установочные размеры', description: 'Установочные размеры должны быть указаны', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Размеры', standardCode: 'ГОСТ 2.307-2011' },
  { code: 'R-SEM-016', name: 'Присоединительные размеры', description: 'Присоединительные размеры должны быть указаны', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Размеры', standardCode: 'ГОСТ 2.307-2011' },
  { code: 'R-SEM-017', name: 'Маркировка изделия', description: 'Должно быть указание о маркировке', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Маркировка', standardCode: 'ГОСТ 2.314-68' },
  { code: 'R-SEM-018', name: 'Клеймо изготовителя', description: 'Должно быть указание о клейме', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Клеймо', standardCode: 'ГОСТ 2.314-68' },
  { code: 'R-SEM-019', name: 'Упаковка и консервация', description: 'Должны быть указания по упаковке и консервации', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Упаковка', standardCode: 'ГОСТ 2.418-77' },
  { code: 'R-SEM-020', name: 'Транспортирование', description: 'Должны быть указания по транспортированию', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Транспортировка', standardCode: 'ГОСТ 2.601-2019' },
  { code: 'R-SEM-021', name: 'Хранение', description: 'Должны быть указания по хранению', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Хранение', standardCode: 'ГОСТ 2.601-2019' },
  { code: 'R-SEM-022', name: 'Утилизация', description: 'Должны быть указания по утилизации', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Утилизация', standardCode: 'ГОСТ 2.601-2019' },
  { code: 'R-SEM-023', name: 'Безопасность при работе', description: 'Должны быть указания по безопасности', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Безопасность', standardCode: 'ГОСТ 12.2.003-91' },
  { code: 'R-SEM-024', name: 'Пожаробезопасность', description: 'Должны быть указания по пожаробезопасности', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Пожар', standardCode: 'ГОСТ 12.1.004-91' },
  { code: 'R-SEM-025', name: 'Экологичность', description: 'Должны быть указания по экологичности', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Экология', standardCode: 'ГОСТ Р ИСО 14001-2016' },
  { code: 'R-SEM-026', name: 'Гарантийные обязательства', description: 'Должны быть указаны гарантийные обязательства', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Гарантия', standardCode: 'ГОСТ 2.601-2019' },
  { code: 'R-SEM-027', name: 'Срок службы', description: 'Должен быть указан срок службы', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Срок службы', standardCode: 'ГОСТ 2.601-2019' },
  { code: 'R-SEM-028', name: 'Ремонтопригодность', description: 'Должны быть указания по ремонтопригодности', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Ремонт', standardCode: 'ГОСТ 2.602-2013' },
  { code: 'R-SEM-029', name: 'Запасные части', description: 'Должен быть перечень ЗИП', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'ЗИП', standardCode: 'ГОСТ 2.601-2019' },
  { code: 'R-SEM-030', name: 'Инструкция по эксплуатации', description: 'Должна быть ссылка на руководство по эксплуатации', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Эксплуатация', standardCode: 'ГОСТ 2.601-2019' },
  // Формат и листы (R-FORMAT-004..015)
  { code: 'R-FORMAT-004', name: 'Формат с рамкой', description: 'Внешняя рамка на 5 мм от края', category: 'format', method: 'vision', severity: 'medium', gostField: 'Формат', standardCode: 'ГОСТ 2.301-68' },
  { code: 'R-FORMAT-005', name: 'Штамп в правом нижнем углу', description: 'Основная надпись в правом нижнем углу', category: 'format', method: 'vision', severity: 'high', gostField: 'Формат', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-FORMAT-006', name: 'Поле чертежа внутри рамки', description: 'Графическое содержание внутри рамки', category: 'format', method: 'vision', severity: 'medium', gostField: 'Формат', standardCode: 'ГОСТ 2.301-68' },
  { code: 'R-FORMAT-007', name: 'Рамка основной надписи', description: 'Рамка основной надписи 185×55 мм', category: 'format', method: 'vision', severity: 'medium', gostField: 'Формат', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-FORMAT-008', name: 'Дополнительная графа 14', description: 'Графа 14 (обозначение) повёрнута на 90°', category: 'format', method: 'vision', severity: 'low', gostField: 'Формат', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-FORMAT-009', name: 'Линии рамки', description: 'Линии рамки — сплошные основные', category: 'format', method: 'vision', severity: 'low', gostField: 'Формат', standardCode: 'ГОСТ 2.303-68' },
  { code: 'R-FORMAT-010', name: 'Толщина линий', description: 'Толщина основной линии 0,5-1,4 мм', category: 'format', method: 'vision', severity: 'low', gostField: 'Формат', standardCode: 'ГОСТ 2.303-68' },
  { code: 'R-FORMAT-011', name: 'Шрифт надписей', description: 'Шрифт соответствует ГОСТ 2.304', category: 'format', method: 'vision', severity: 'low', gostField: 'Формат', standardCode: 'ГОСТ 2.304-81' },
  { code: 'R-FORMAT-012', name: 'Размер шрифта', description: 'Размер шрифта не менее 2,5 мм', category: 'format', method: 'vision', severity: 'low', gostField: 'Формат', standardCode: 'ГОСТ 2.304-81' },
  { code: 'R-FORMAT-013', name: 'Ориентация формата', description: 'Для A4 — вертикальная, для A3+ — горизонтальная', category: 'format', method: 'vision', severity: 'low', gostField: 'Формат', standardCode: 'ГОСТ 2.301-68' },
  { code: 'R-FORMAT-014', name: 'Масштаб в штампе', description: 'Масштаб указывается в графе 6', category: 'format', method: 'vision', severity: 'low', gostField: 'Формат', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-FORMAT-015', name: 'Литера в графе 2', description: 'Литера указывается в графе 2 штампа', category: 'format', method: 'vision', severity: 'low', gostField: 'Формат', standardCode: 'ГОСТ 2.104-2006' },
  // Технические требования (R-TT-005..020)
  { code: 'R-TT-005', name: 'ТТ нумеруются', description: 'Пункты ТТ нумеруются', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'ТТ', standardCode: 'ГОСТ 2.316-2008' },
  { code: 'R-TT-006', name: 'ТТ расположены над штампом', description: 'ТТ располагаются над штампом', category: 'stamp', method: 'vision', severity: 'low', gostField: 'ТТ', standardCode: 'ГОСТ 2.316-2008' },
  { code: 'R-TT-007', name: 'ТТ с заголовком', description: 'Заголовок "Технические требования" не подчёркивается', category: 'stamp', method: 'vision', severity: 'low', gostField: 'ТТ', standardCode: 'ГОСТ 2.316-2008' },
  { code: 'R-TT-008', name: 'Неуказанные фаски', description: 'Неуказанные фаски должны быть указаны в ТТ', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'ТТ', standardCode: 'ГОСТ 2.307-2011' },
  { code: 'R-TT-009', name: 'Неуказанные радиусы скруглений', description: 'Неуказанные радиусы скруглений в ТТ', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'ТТ', standardCode: 'ГОСТ 2.307-2011' },
  { code: 'R-TT-010', name: 'Допуски на свободные размеры', description: 'Допуски на свободные размеры в ТТ', category: 'stamp', method: 'semantic', severity: 'medium', gostField: 'ТТ', standardCode: 'ГОСТ 30893.1-2002' },
  { code: 'R-TT-011', name: 'Шероховатость неуказанная', description: 'Неуказанная шероховатость в ТТ', category: 'stamp', method: 'semantic', severity: 'medium', gostField: 'ТТ', standardCode: 'ГОСТ 2.309-73' },
  { code: 'R-TT-012', name: 'Допуски формы неуказанные', description: 'Неуказанные допуски формы в ТТ', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'ТТ', standardCode: 'ГОСТ 30893.2-2002' },
  { code: 'R-TT-013', name: 'Маркировка в ТТ', description: 'Указания по маркировке в ТТ', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'ТТ', standardCode: 'ГОСТ 2.314-68' },
  { code: 'R-TT-014', name: 'Покрытие в ТТ', description: 'Указания по покрытию в ТТ', category: 'stamp', method: 'semantic', severity: 'medium', gostField: 'ТТ', standardCode: 'ГОСТ 9.032-74' },
  { code: 'R-TT-015', name: 'Контроль качества в ТТ', description: 'Указания по контролю качества в ТТ', category: 'stamp', method: 'semantic', severity: 'medium', gostField: 'ТТ', standardCode: 'ГОСТ 2.316-2008' },
  { code: 'R-TT-016', name: 'Сварка в ТТ', description: 'Указания по сварке в ТТ (при наличии)', category: 'stamp', method: 'semantic', severity: 'medium', gostField: 'ТТ', standardCode: 'ГОСТ 2.312-72' },
  { code: 'R-TT-017', name: 'Термообработка в ТТ', description: 'Указания по термообработке (при необходимости)', category: 'stamp', method: 'semantic', severity: 'medium', gostField: 'ТТ', standardCode: 'ГОСТ 2.316-2008' },
  { code: 'R-TT-018', name: 'Испытания в ТТ', description: 'Указания по испытаниям (при необходимости)', category: 'stamp', method: 'semantic', severity: 'medium', gostField: 'ТТ', standardCode: 'ГОСТ 2.316-2008' },
  { code: 'R-TT-019', name: 'Транспортирование в ТТ', description: 'Указания по транспортированию в ТТ', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'ТТ', standardCode: 'ГОСТ 2.316-2008' },
  { code: 'R-TT-020', name: 'Хранение в ТТ', description: 'Указания по хранению в ТТ', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'ТТ', standardCode: 'ГОСТ 2.316-2008' },
  // Перечень ГОСТ (R-GOST-003..015)
  { code: 'R-GOST-003', name: 'Перечень ГОСТ отсортирован', description: 'ГОСТ в перечне отсортированы по номеру', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Перечень ГОСТ', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-GOST-004', name: 'Перечень ГОСТ с обозначением', description: 'ГОСТ указывается с полным обозначением (номер-год)', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Перечень ГОСТ', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-GOST-005', name: 'Перечень ГОСТ без дубликатов', description: 'В перечне не должно быть дубликатов ГОСТ', category: 'stamp', method: 'deterministic', severity: 'medium', gostField: 'Перечень ГОСТ', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-GOST-006', name: 'Перечень ГОСТ в алфавитном порядке', description: 'ГОСТ в перечне — по возрастанию', category: 'stamp', method: 'deterministic', severity: 'low', gostField: 'Перечень ГОСТ', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-GOST-007', name: 'ГОСТ 2.104 в перечне', description: 'При использовании штампа ГОСТ 2.104 должен быть в перечне', category: 'stamp', method: 'semantic', severity: 'medium', gostField: 'Перечень ГОСТ', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-GOST-008', name: 'ГОСТ 2.301 в перечне', description: 'При использовании форматов ГОСТ 2.301 в перечне', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Перечень ГОСТ', standardCode: 'ГОСТ 2.301-68' },
  { code: 'R-GOST-009', name: 'ГОСТ 2.302 в перечне', description: 'При использовании масштаба ГОСТ 2.302 в перечне', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Перечень ГОСТ', standardCode: 'ГОСТ 2.302-68' },
  { code: 'R-GOST-010', name: 'ГОСТ 2.307 в перечне', description: 'При наличии размеров ГОСТ 2.307 в перечне', category: 'stamp', method: 'semantic', severity: 'medium', gostField: 'Перечень ГОСТ', standardCode: 'ГОСТ 2.307-2011' },
  { code: 'R-GOST-011', name: 'ГОСТ 2.309 в перечне', description: 'При наличии шероховатости ГОСТ 2.309 в перечне', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Перечень ГОСТ', standardCode: 'ГОСТ 2.309-73' },
  { code: 'R-GOST-012', name: 'ГОСТ 2.312 в перечне', description: 'При наличии сварных швов ГОСТ 2.312 в перечне', category: 'stamp', method: 'semantic', severity: 'high', gostField: 'Перечень ГОСТ', standardCode: 'ГОСТ 2.312-72' },
  { code: 'R-GOST-013', name: 'ГОСТ 2.316 в перечне', description: 'При наличии ТТ ГОСТ 2.316 в перечне', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Перечень ГОСТ', standardCode: 'ГОСТ 2.316-2008' },
  { code: 'R-GOST-014', name: 'ГОСТ 2.109 в перечне', description: 'Для чертежей ГОСТ 2.109 в перечне', category: 'stamp', method: 'semantic', severity: 'medium', gostField: 'Перечень ГОСТ', standardCode: 'ГОСТ 2.109-73' },
  { code: 'R-GOST-015', name: 'ГОСТ материала в перечне', description: 'ГОСТ материала должен быть в перечне (повтор R-MAT-003)', category: 'stamp', method: 'semantic', severity: 'high', gostField: 'Перечень ГОСТ', standardCode: 'ГОСТ 2.104-2006' },
  // Комплектность (R-SET-003..010)
  { code: 'R-SET-003', name: 'Комплектность: спецификация', description: 'Для сборочного чертежа — спецификация', category: 'stamp', method: 'semantic', severity: 'high', gostField: 'Комплектность', standardCode: 'ГОСТ 2.102-2013' },
  { code: 'R-SET-004', name: 'Комплектность: чертежи деталей', description: 'Для каждой детали — отдельный чертеж', category: 'stamp', method: 'semantic', severity: 'medium', gostField: 'Комплектность', standardCode: 'ГОСТ 2.102-2013' },
  { code: 'R-SET-005', name: 'Комплектность: ТУ', description: 'При необходимости — технические условия', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Комплектность', standardCode: 'ГОСТ 2.114-2016' },
  { code: 'R-SET-006', name: 'Комплектность: программа испытаний', description: 'При необходимости — программа испытаний', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Комплектность', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SET-007', name: 'Комплектность: паспорт', description: 'При необходимости — паспорт', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Комплектность', standardCode: 'ГОСТ 2.601-2019' },
  { code: 'R-SET-008', name: 'Комплектность: руководство по эксплуатации', description: 'При необходимости — РЭ', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Комплектность', standardCode: 'ГОСТ 2.601-2019' },
  { code: 'R-SET-009', name: 'Комплектность: ведомость', description: 'При необходимости — ведомость', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Комплектность', standardCode: 'ГОСТ 2.106-96' },
  { code: 'R-SET-010', name: 'Комплектность: расчёты', description: 'При необходимости — расчёты', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Комплектность', standardCode: 'ГОСТ 2.102-2013' },
  // Литера и стадия (R-LETTER-002..010, R-STAGE-003..010)
  { code: 'R-LETTER-002', name: 'Литера О для опытного образца', description: 'Литера О — для опытного образца', category: 'stamp', method: 'semantic', severity: 'medium', gostField: 'Литера', standardCode: 'ГОСТ 2.103-2013' },
  { code: 'R-LETTER-003', name: 'Литера А для серийного', description: 'Литера А — для установочной серии', category: 'stamp', method: 'semantic', severity: 'medium', gostField: 'Литера', standardCode: 'ГОСТ 2.103-2013' },
  { code: 'R-LETTER-004', name: 'Литера Б для серийного', description: 'Литера Б — для серийного производства', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Литера', standardCode: 'ГОСТ 2.103-2013' },
  { code: 'R-LETTER-005', name: 'Литера соответствует стадии', description: 'Литера должна соответствовать стадии', category: 'stamp', method: 'semantic', severity: 'medium', gostField: 'Литера', standardCode: 'ГОСТ 2.103-2013' },
  { code: 'R-LETTER-006', name: 'Литера в графе 2', description: 'Литера в графе 2 штампа', category: 'stamp', method: 'vision', severity: 'low', gostField: 'Литера', standardCode: 'ГОСТ 2.104-2006' },
  { code: 'R-STAGE-003', name: 'Стадия ЭП для эскизного', description: 'Стадия ЭП — эскизный проект', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Стадия', standardCode: 'ГОСТ 2.103-2013' },
  { code: 'R-STAGE-004', name: 'Стадия ТП для технического', description: 'Стадия ТП — технический проект', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Стадия', standardCode: 'ГОСТ 2.103-2013' },
  { code: 'R-STAGE-005', name: 'Стадия РД для рабочего', description: 'Стадия РД — рабочая документация', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Стадия', standardCode: 'ГОСТ 2.103-2013' },
  { code: 'R-STAGE-006', name: 'Стадия РК для единичного', description: 'Стадия РК — рабочая для единичного производства', category: 'stamp', method: 'semantic', severity: 'low', gostField: 'Стадия', standardCode: 'ГОСТ 2.103-2013' },
  { code: 'R-STAGE-007', name: 'Стадия соответствует литера', description: 'Стадия и литера должны быть согласованы', category: 'stamp', method: 'deterministic', severity: 'medium', gostField: 'Стадия/Литера', standardCode: 'ГОСТ 2.103-2013' },
  // Безопасность (R-SAFE-001..015)
  { code: 'R-SAFE-001', name: 'Указание электробезопасности', description: 'Для эл. оборудования — требования электробезопасности', category: 'semantic', method: 'semantic', severity: 'high', gostField: 'Безопасность', standardCode: 'ГОСТ 12.1.019-79' },
  { code: 'R-SAFE-002', name: 'Указание заземления', description: 'Для эл. оборудования — указание о заземлении', category: 'semantic', method: 'semantic', severity: 'high', gostField: 'Безопасность', standardCode: 'ГОСТ 12.1.030-81' },
  { code: 'R-SAFE-003', name: 'Степень защиты IP', description: 'Для эл. оборудования — указание степени защиты IP', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Безопасность', standardCode: 'ГОСТ 14254-2015' },
  { code: 'R-SAFE-004', name: 'Взрывозащита', description: 'Для взрывоопасных зон — указание взрывозащиты', category: 'semantic', method: 'semantic', severity: 'high', gostField: 'Безопасность', standardCode: 'ГОСТ Р 51330.0-99' },
  { code: 'R-SAFE-005', name: 'Пожарная безопасность', description: 'Указания по пожарной безопасности', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Безопасность', standardCode: 'ГОСТ 12.1.004-91' },
  { code: 'R-SAFE-006', name: 'Шум и вибрация', description: 'Указания по шуму и вибрации', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Безопасность', standardCode: 'ГОСТ 12.1.003-2014' },
  { code: 'R-SAFE-007', name: 'СИЗ', description: 'Указания о СИЗ при работе', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Безопасность', standardCode: 'ГОСТ 12.4.011-89' },
  { code: 'R-SAFE-008', name: 'Экологичность', description: 'Указания по экологичности', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Экология', standardCode: 'ГОСТ Р ИСО 14001-2016' },
  { code: 'R-SAFE-009', name: 'Утилизация', description: 'Указания по утилизации', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Экология', standardCode: 'ГОСТ 2.601-2019' },
  { code: 'R-SAFE-010', name: 'Опасные вещества', description: 'При использовании опасных веществ — указания', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Безопасность', standardCode: 'ГОСТ 12.1.007-76' },
  { code: 'R-SAFE-011', name: 'Сварка — ТБ', description: 'При сварке — требования безопасности', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Безопасность', standardCode: 'ГОСТ 12.3.003-86' },
  { code: 'R-SAFE-012', name: 'Погрузка — ТБ', description: 'При погрузке — требования безопасности', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Безопасность', standardCode: 'ГОСТ 12.3.009-76' },
  { code: 'R-SAFE-013', name: 'Термообработка — ТБ', description: 'При термообработке — требования безопасности', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Безопасность', standardCode: 'ГОСТ 12.3.004-75' },
  { code: 'R-SAFE-014', name: 'ЭМС', description: 'Указания по электромагнитной совместимости', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'ЭМС', standardCode: 'ГОСТ 32020-2013' },
  { code: 'R-SAFE-015', name: 'Климатическое исполнение в ТТ', description: 'Климатическое исполнение в ТТ', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Климат', standardCode: 'ГОСТ 15150-69' },
  // Системы качества (R-QA-001..010)
  { code: 'R-QA-001', name: 'Обозначение по ИСО 9001', description: 'Документ соответствует требованиям ИСО 9001', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Качество', standardCode: 'ГОСТ Р ИСО 9001-2015' },
  { code: 'R-QA-002', name: 'Версия документа', description: 'Должна быть указана версия документа', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Версия', standardCode: 'ГОСТ 2.503-2013' },
  { code: 'R-QA-003', name: 'Дата последнего изменения', description: 'Должна быть указана дата последнего изменения', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Версия', standardCode: 'ГОСТ 2.503-2013' },
  { code: 'R-QA-004', name: 'Автор последнего изменения', description: 'Должен быть указан автор последнего изменения', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Версия', standardCode: 'ГОСТ 2.503-2013' },
  { code: 'R-QA-005', name: 'Лист регистрации изменений', description: 'Должен быть лист регистрации изменений', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Изменения', standardCode: 'ГОСТ 2.503-2013' },
  { code: 'R-QA-006', name: 'Подпись в листе изменений', description: 'В листе изменений должны быть подписи', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Изменения', standardCode: 'ГОСТ 2.503-2013' },
  { code: 'R-QA-007', name: 'Обоснование изменения', description: 'Должно быть обоснование изменения', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Изменения', standardCode: 'ГОСТ 2.503-2013' },
  { code: 'R-QA-008', name: 'Согласование изменения', description: 'Изменения должны быть согласованы', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Изменения', standardCode: 'ГОСТ 2.503-2013' },
  { code: 'R-QA-009', name: 'Утверждение изменения', description: 'Изменения должны быть утверждены', category: 'semantic', method: 'semantic', severity: 'medium', gostField: 'Изменения', standardCode: 'ГОСТ 2.503-2013' },
  { code: 'R-QA-010', name: 'Архивная копия', description: 'Должна быть архивная копия предыдущей версии', category: 'semantic', method: 'semantic', severity: 'low', gostField: 'Архив', standardCode: 'ГОСТ 2.501-2013' },
]

async function main() {
  console.log(`📚 Adding ${MORE_STANDARDS.length} more standards...`)
  let sInserted = 0, sUpdated = 0
  for (const s of MORE_STANDARDS) {
    const existing = await db.standard.findUnique({ where: { code: s.code } })
    if (existing) {
      sUpdated++
    } else {
      await db.standard.create({ data: { ...s, status: 'active', source: 'cntd' } })
      sInserted++
    }
  }
  console.log(`  ✓ ${sInserted} new, ${sUpdated} already existed`)
  
  console.log(`📐 Adding ${MORE_RULES.length} more rules...`)
  let rInserted = 0, rUpdated = 0
  for (const r of MORE_RULES) {
    const std = r.standardCode ? await db.standard.findUnique({ where: { code: r.standardCode } }) : null
    const existing = await db.rule.findUnique({ where: { code: r.code } })
    if (existing) {
      rUpdated++
    } else {
      await db.rule.create({
        data: {
          code: r.code, name: r.name, description: r.description,
          category: r.category, method: r.method, severity: r.severity,
          gostField: r.gostField, enabled: true, standardId: std?.id ?? null,
        },
      })
      rInserted++
    }
  }
  console.log(`  ✓ ${rInserted} new, ${rUpdated} already existed`)
  
  const total = await db.standard.count()
  const rulesCount = await db.rule.count()
  console.log(`\n📊 Final state: ${total} standards, ${rulesCount} rules`)
}

main().catch(e => { console.error(e); process.exit(1) }).finally(() => db.$disconnect())
